# Generated by Django 5.1.15 on 2026-07-31 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_mailsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailsettings',
            name='use_default',
            field=models.BooleanField(default=True),
        ),
    ]
