# Generated by Django 5.1.15 on 2026-08-01 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_session_timeout_minutes'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('landlord', 'Wynajmujący'), ('tenant', 'Najemca')], default='landlord', max_length=16),
        ),
    ]
