# Generated by Django 5.1.15 on 2026-08-03 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_email_verified_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailsettings',
            name='reply_to',
            field=models.EmailField(blank=True, max_length=255),
        ),
    ]
