# Generated by Django 5.1.15 on 2026-08-03 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_mailsettings_reply_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailsettings',
            name='test_mode',
            field=models.BooleanField(default=False),
        ),
    ]
