# Generated by Django 5.1.15 on 2026-08-03 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_mailsettings_test_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailsettings',
            name='test_recipient',
            field=models.EmailField(blank=True, max_length=255),
        ),
    ]
