# Generated by Django 5.1.15 on 2026-07-30 08:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=32)),
                ('is_individual', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_fees', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FeeCalculation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stamp', models.DateTimeField()),
                ('period_start', models.DateTimeField()),
                ('period_end', models.DateTimeField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calculations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-period_start'],
            },
        ),
        migrations.CreateModel(
            name='Flat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('city', models.CharField(max_length=32)),
                ('street', models.CharField(max_length=64)),
                ('building_no', models.CharField(blank=True, max_length=15)),
                ('flat_no', models.CharField(blank=True, max_length=15)),
                ('flat_size', models.PositiveIntegerField(blank=True, help_text='m²', null=True)),
                ('code', models.CharField(max_length=16)),
                ('room_count', models.PositiveIntegerField(blank=True, null=True)),
                ('created', models.DateTimeField(blank=True, null=True)),
                ('rental_start', models.DateTimeField(blank=True, null=True)),
                ('color', models.CharField(blank=True, max_length=15)),
                ('mortgage_start', models.DateTimeField(blank=True, null=True)),
                ('mortgage_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('mortgage_capital', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('mortgage_interest', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flats', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['city', 'street'],
            },
        ),
        migrations.CreateModel(
            name='FeeCalculationTenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_name', models.CharField(blank=True, max_length=64)),
                ('contract_number', models.CharField(blank=True, max_length=64)),
                ('email', models.EmailField(blank=True, max_length=64)),
                ('calculation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenants', to='core.feecalculation')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calc_tenants', to=settings.AUTH_USER_MODEL)),
                ('flat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calc_tenants', to='core.flat')),
            ],
        ),
        migrations.CreateModel(
            name='FeeCalculationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fee_type', models.CharField(choices=[('Counter', 'Counter'), ('Admin', 'Admin')], max_length=8)),
                ('name', models.CharField(max_length=64)),
                ('usage', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('calculation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.feecalculation')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calc_items', to=settings.AUTH_USER_MODEL)),
                ('flat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calc_items', to='core.flat')),
            ],
        ),
        migrations.AddField(
            model_name='feecalculation',
            name='flat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calculations', to='core.flat'),
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('contract_number', models.CharField(blank=True, max_length=32)),
                ('tenant_name', models.CharField(blank=True, max_length=64)),
                ('email', models.EmailField(blank=True, max_length=64)),
                ('phone', models.CharField(blank=True, max_length=32)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('deposit', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('contract_date', models.DateField(blank=True, null=True)),
                ('contract_start', models.DateField(blank=True, null=True)),
                ('contract_end', models.DateField(blank=True, null=True)),
                ('payment_day', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to=settings.AUTH_USER_MODEL)),
                ('flat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='core.flat')),
            ],
            options={
                'ordering': ['-contract_start'],
            },
        ),
        migrations.CreateModel(
            name='AdminFeePrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_date', models.DateTimeField(blank=True, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('admin_fee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='core.adminfee')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_fee_prices', to=settings.AUTH_USER_MODEL)),
                ('flat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_fee_prices', to='core.flat')),
            ],
            options={
                'ordering': ['admin_fee', 'price_date'],
            },
        ),
        migrations.AddField(
            model_name='adminfee',
            name='flat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_fees', to='core.flat'),
        ),
        migrations.CreateModel(
            name='MeterDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('unit', models.CharField(blank=True, choices=[('kWh', 'kWh'), ('m³', 'm³')], max_length=8)),
                ('flat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meters', to='core.flat')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meters', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MeterPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_date', models.DateField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=4, max_digits=10)),
                ('flat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meter_prices', to='core.flat')),
                ('meter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='core.meterdefinition')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meter_prices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['meter', 'price_date'],
            },
        ),
        migrations.CreateModel(
            name='MeterReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_date', models.DateField()),
                ('value', models.DecimalField(decimal_places=3, max_digits=12)),
                ('flat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='core.flat')),
                ('meter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='core.meterdefinition')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['meter', 'read_date'],
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('room_no', models.PositiveIntegerField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=32)),
                ('size', models.PositiveIntegerField(blank=True, help_text='m²', null=True)),
                ('beds', models.PositiveIntegerField(blank=True, null=True)),
                ('fee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('deposit', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('flat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='core.flat')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['flat', 'room_no'],
            },
        ),
        migrations.CreateModel(
            name='LedgerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_desc', models.CharField(blank=True, max_length=64)),
                ('notes', models.TextField(blank=True)),
                ('record_date', models.DateTimeField(blank=True, null=True)),
                ('created', models.DateTimeField(blank=True, null=True)),
                ('modified', models.DateTimeField(blank=True, null=True)),
                ('amount_in_not_taxable', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('amount_in_taxable', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('amount_out', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_mortgage', models.BooleanField(blank=True, null=True)),
                ('contract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_entries', to='core.contract')),
                ('flat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledger_entries', to='core.flat')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledger_entries', to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_entries', to='core.room')),
            ],
            options={
                'verbose_name_plural': 'ledger entries',
                'ordering': ['-record_date'],
            },
        ),
        migrations.AddField(
            model_name='contract',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='core.room'),
        ),
        migrations.CreateModel(
            name='TaxDue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(blank=True, help_text='YYYY-MM', max_length=7)),
                ('tax_date', models.DateTimeField(blank=True, null=True)),
                ('tax_amount', models.IntegerField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tax_due', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'tax due',
                'ordering': ['-period'],
            },
        ),
        migrations.CreateModel(
            name='TaxMode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cal_year', models.PositiveIntegerField(blank=True, null=True)),
                ('mode', models.CharField(blank=True, choices=[('r', 'Ryczałt'), ('L18', 'Skala 18%'), ('L32', 'Skala 32%')], max_length=3)),
                ('period', models.CharField(blank=True, choices=[('m', 'Monthly'), ('q', 'Quarterly')], max_length=1)),
                ('reminder', models.PositiveIntegerField(blank=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tax_modes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
