# Generated by Django 5.1.15 on 2026-07-30 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taxmode',
            name='mode',
        ),
    ]
