# Generated by Django 5.1.15 on 2026-07-31 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_normalize_meter_units'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ledgerentry',
            name='amount_out',
        ),
        migrations.RemoveField(
            model_name='ledgerentry',
            name='cost',
        ),
    ]
