# Generated by Django 5.1.15 on 2026-07-31 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_ledgerentry_amount_out_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ledgerentry',
            name='amount_in_not_taxable',
        ),
    ]
