# Generated by Django 5.1.15 on 2026-07-31 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_ledgerentry_amount_in_not_taxable'),
    ]

    operations = [
        migrations.AddField(
            model_name='ledgerentry',
            name='billing_period',
            field=models.DateField(blank=True, null=True),
        ),
    ]
