# Generated by Django 5.1.15 on 2026-07-31 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_backfill_billing_period'),
    ]

    operations = [
        migrations.AddField(
            model_name='ledgerentry',
            name='kind',
            field=models.CharField(choices=[('rent', 'Czynsz najmu'), ('fee', 'Pozostałe opłaty')], db_index=True, default='rent', max_length=8),
        ),
    ]
