# Generated by Django 5.1.15 on 2026-08-03 20:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_emailtemplate_emaillog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Fund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('monthly_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('flat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='funds', to='core.flat')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='funds', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['flat', 'name'],
            },
        ),
        migrations.CreateModel(
            name='FundContribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contributed_on', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('note', models.CharField(blank=True, max_length=64)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('flat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fund_contributions', to='core.flat')),
                ('fund', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributions', to='core.fund')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fund_contributions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-contributed_on', '-id'],
            },
        ),
        migrations.CreateModel(
            name='FundExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spent_on', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.CharField(max_length=64)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('flat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fund_expenses', to='core.flat')),
                ('fund', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='core.fund')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fund_expenses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-spent_on', '-id'],
            },
        ),
    ]
