# Generated by Django 5.1.15 on 2026-08-03 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_fund_fundcontribution_fundexpense'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feecalculationitem',
            name='fee_type',
            field=models.CharField(choices=[('Counter', 'Counter'), ('Admin', 'Admin'), ('Fund', 'Fundusze')], max_length=8),
        ),
    ]
