# Generated by Django 5.1.15 on 2026-08-03 20:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_feecalculationitem_fee_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='ledgerentry',
            name='settlement_tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_entries', to='core.feecalculationtenant'),
        ),
    ]
