# Generated by Django 5.1.15 on 2026-08-07 08:58

import django.db.models.deletion
from django.db import migrations, models


def backfill_contract(apps, schema_editor):
    """Resolve existing snapshots to their contract by (owner, number)."""
    FeeCalculationTenant = apps.get_model("core", "FeeCalculationTenant")
    Contract = apps.get_model("core", "Contract")

    by_key: dict[tuple, list] = {}
    for c in Contract.objects.all():
        if c.contract_number:
            by_key.setdefault((c.owner_id, c.contract_number), []).append(c)

    for t in FeeCalculationTenant.objects.filter(
        contract__isnull=True
    ).select_related("calculation"):
        if not t.contract_number:
            continue
        cands = by_key.get((t.owner_id, t.contract_number))
        if not cands:
            continue
        chosen = cands[0]
        if len(cands) > 1:  # renewals share a number: pick the overlapping one
            ps = t.calculation.period_start.date()
            pe = t.calculation.period_end.date()
            for c in cands:
                if c.contract_start and c.contract_start <= pe and (
                    c.contract_end is None or c.contract_end >= ps
                ):
                    chosen = c
                    break
        t.contract_id = chosen.id
        t.save(update_fields=["contract"])


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_ledgerentry_settlement_tenant'),
    ]

    operations = [
        migrations.AddField(
            model_name='feecalculationtenant',
            name='contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='settlement_tenants', to='core.contract'),
        ),
        migrations.RunPython(backfill_contract, migrations.RunPython.noop),
    ]
