# Generated by Django 5.1.15 on 2026-08-07 10:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_feecalculationtenant_contract'),
    ]

    operations = [
        migrations.AddField(
            model_name='emaillog',
            name='settlement_tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_logs', to='core.feecalculationtenant'),
        ),
        migrations.AddField(
            model_name='flat',
            name='owner_bcc_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
