# Generated by Django 5.1.15 on 2026-08-07 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_flat_bcc_and_emaillog_tenant'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='hard_stop',
            field=models.BooleanField(default=False),
        ),
    ]
