# Generated by Django 5.1.15 on 2026-08-07 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_contract_hard_stop'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='renewal_proposed_until',
            field=models.DateField(blank=True, null=True),
        ),
    ]
