# Generated by Django 5.1.15 on 2026-08-08 09:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_contract_renewal_proposed_until'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FundRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('flat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fund_rates', to='core.flat')),
                ('fund', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates', to='core.fund')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fund_rates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['fund', 'rate_date'],
            },
        ),
    ]
