# Generated by Django 5.1.15 on 2026-08-08 11:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_fundrate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeeItemPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fee_type', models.CharField(max_length=8)),
                ('name', models.CharField(max_length=64)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('record_date', models.DateTimeField(blank=True, null=True)),
                ('billing_period', models.DateField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('flat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_item_payments', to='core.flat')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='core.feecalculationitem')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_item_payments', to=settings.AUTH_USER_MODEL)),
                ('settlement_tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_payments', to='core.feecalculationtenant')),
            ],
            options={
                'ordering': ['-billing_period', 'fee_type', 'id'],
            },
        ),
    ]
