# Generated by Django 5.1.15 on 2026-08-11 12:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_emailtemplate_payment_reminder'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='adminfee',
            name='is_invoice',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='AdminFeeInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('admin_fee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='core.adminfee')),
                ('flat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_fee_invoices', to='core.flat')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_fee_invoices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-period'],
                'constraints': [models.UniqueConstraint(fields=('admin_fee', 'period'), name='uniq_adminfee_invoice_period')],
            },
        ),
    ]
