# Generated by Django 5.1.15 on 2026-08-11 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_adminfee_is_invoice_adminfeeinvoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminfee',
            name='bill_in_advance',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='feecalculationitem',
            name='bill_in_advance',
            field=models.BooleanField(default=False),
        ),
    ]
