from django.urls import path

from . import views

app_name = "core"

urlpatterns = [
    path("", views.dashboard, name="dashboard"),
    path("flats/", views.flats, name="flats"),
    path("flats/add/", views.add_flat, name="add_flat"),
    path("flats/<int:pk>/edit/", views.FlatUpdate.as_view(), name="edit_flat"),
    path("flats/<int:pk>/delete/", views.FlatDelete.as_view(), name="delete_flat"),
    path("fees/add/", views.fee_add, name="fee_add"),
    path("flats/<int:pk>/fees/", views.flat_fees, name="flat_fees"),
    path("flats/<int:pk>/fees/<int:fee_id>/edit/", views.edit_fee, name="edit_fee"),
    path("flats/<int:pk>/fees/<int:fee_id>/delete/", views.delete_fee, name="delete_fee"),
    path(
        "flats/<int:pk>/fees/<int:fee_id>/price/",
        views.add_fee_price,
        name="add_fee_price",
    ),
    path(
        "flats/<int:pk>/fees/price/<int:price_id>/delete/",
        views.delete_fee_price,
        name="delete_fee_price",
    ),
    path(
        "flats/<int:pk>/meters/<int:meter_id>/edit/",
        views.flat_meter_edit,
        name="flat_meter_edit",
    ),
    path(
        "flats/<int:pk>/meters/<int:meter_id>/delete/",
        views.flat_meter_delete,
        name="flat_meter_delete",
    ),
    path(
        "flats/<int:pk>/meters/<int:meter_id>/price/",
        views.add_meter_price,
        name="add_meter_price",
    ),
    path(
        "flats/<int:pk>/meters/price/<int:price_id>/delete/",
        views.delete_meter_price,
        name="delete_meter_price",
    ),
    path("rooms/", views.rooms, name="rooms"),
    path("rooms/add/", views.RoomCreate.as_view(), name="add_room"),
    path("rooms/<int:pk>/edit/", views.RoomUpdate.as_view(), name="edit_room"),
    path("rooms/<int:pk>/delete/", views.RoomDelete.as_view(), name="delete_room"),
    path("contracts/", views.contracts, name="contracts"),
    path("contracts/add/", views.ContractCreate.as_view(), name="add_contract"),
    path("contracts/<int:pk>/edit/", views.ContractUpdate.as_view(), name="edit_contract"),
    path(
        "contracts/<int:pk>/delete/",
        views.ContractDelete.as_view(),
        name="delete_contract",
    ),
    path("records/", views.records, name="records"),
    path("records/add/", views.RecordCreate.as_view(), name="add_record"),
    path("records/<int:pk>/edit/", views.RecordUpdate.as_view(), name="edit_record"),
    path("records/<int:pk>/delete/", views.RecordDelete.as_view(), name="delete_record"),
    path("calculations/", views.calculations, name="calculations"),
    path("calculations/new/", views.run_settlement, name="run_settlement"),
    path("calculations/<int:pk>/", views.calculation_detail, name="calculation_detail"),
    path(
        "calculations/<int:pk>/preview/<int:tenant_pk>/",
        views.settlement_email_preview,
        name="settlement_email_preview",
    ),
    path(
        "calculations/<int:pk>/delete/",
        views.delete_settlement,
        name="delete_settlement",
    ),
    path(
        "calculations/<int:pk>/email/",
        views.email_settlement,
        name="email_settlement",
    ),
    path("readings/add/", views.add_reading, name="add_reading"),
    path("readings/estimate/", views.estimate_readings, name="estimate_readings"),
    path("readings/<int:pk>/edit/", views.ReadingUpdate.as_view(), name="edit_reading"),
    path(
        "readings/<int:pk>/delete/",
        views.ReadingDelete.as_view(),
        name="delete_reading",
    ),
    path("counters/", views.counters, name="counters"),
    path(
        "counters/flat/<int:flat_id>/delete-readings/",
        views.delete_readings_on_date,
        name="delete_readings_on_date",
    ),
    path("counters/add/", views.MeterCreate.as_view(), name="add_meter"),
    path("counters/<int:pk>/edit/", views.MeterUpdate.as_view(), name="edit_meter"),
    path("counters/<int:pk>/delete/", views.MeterDelete.as_view(), name="delete_meter"),
    path("counters/<int:pk>/readings/", views.meter_readings, name="meter_readings"),
    path("tax/", views.tax, name="tax"),
    path(
        "tax/pay/<int:year>/<int:month>/",
        views.confirm_tax_payment,
        name="confirm_tax_payment",
    ),
    path(
        "tax/payment/<int:pk>/delete/",
        views.delete_tax_payment,
        name="delete_tax_payment",
    ),
    path("forecast/", views.forecast, name="forecast"),
    path("settings/", views.user_settings, name="settings"),
    path("settings/wishlist/", views.wishlist, name="wishlist"),
    path(
        "settings/wishlist/<int:pk>/reply/",
        views.wishlist_reply,
        name="wishlist_reply",
    ),
    path("communication/", views.communication, name="communication"),
    path(
        "communication/templates/add/",
        views.email_template_add,
        name="email_template_add",
    ),
    path(
        "communication/templates/<int:pk>/edit/",
        views.email_template_edit,
        name="email_template_edit",
    ),
    path(
        "communication/templates/<int:pk>/delete/",
        views.email_template_delete,
        name="email_template_delete",
    ),
    path("communication/send/", views.send_adhoc, name="send_adhoc"),
    path("contracts/<int:pk>/invites/", views.contract_invites, name="contract_invites"),
    path("contracts/<int:pk>/invites/new/", views.create_invite, name="create_invite"),
    path("portal/", views.portal, name="portal"),
    path("portal/settlements/", views.portal_settlements, name="portal_settlements"),
    path("portal/payments/", views.portal_payments, name="portal_payments"),
    path("healthz/", views.healthz, name="healthz"),
]
